#### icon
# nf-ple-left_half_circle_thick
# nf-pl-left_hard_divider
# nf-pl-left_hard_divider
# nf-pl-right_hard_divider
# nf-ple-right_half_circle_thick

format = """
$directory\
$git_branch\
[](fg:#242728)\
$fill\
[](fg:#242728)\
\n$character\
"""

right_format = """
$cmd_duration
"""

add_newline = true # 1行改行するか

[directory]
truncation_length = 6
truncation_symbol = '  ' # nf-fa-folder_open
truncate_to_repo = false
home_symbol = '  ~' # nf-fa-home
style = 'fg:#e0af68 bg:#242728'
read_only = ' 󰌾 ' # nf-md-lock
read_only_style = 'fg:#f7768e bg:#242728'
format = '[$path]($style)[$read_only]($read_only_style)'

[git_branch]
symbol = ' ' # nf-fa-github_alt, nf-fa-code_fork
truncation_length = 50 
truncation_symbol = ''
style = 'fg:#e0af68 bg:#242728'
format = '[  $symbol$branch(:$remote_branch)]($style)' # nf-pl-left_soft_divider

[fill]
symbol = ' '
style = 'blue'

[character]
success_symbol = '[❯](bold #9ece6a)'
error_symbol = '[❯](bold red)'

[cmd_duration]
min_time = 1
style = 'fg:#e0af68'
format = "[   $duration]($style)" # nf-pl-right_soft_divider, nf-mdi-clock
